version: '3.8'

services:
  linkedin-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Production settings
      - PRODUCTION_MODE=true
      - MCP_TRANSPORT=sse
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000
      
      # LinkedIn API credentials (set these in .env file)
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    
    # Mount environment file
    env_file:
      - .env
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - linkedin-mcp
    restart: unless-stopped
    profiles:
      - proxy 